name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get commit short SHA
        id: info
        run:
          echo "short_sha=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: |
            docker.io/fnndsc/utils:${{ steps.info.outputs.short_sha }}
            docker.io/fnndsc/utils:latest
            ghcr.io/fnndsc/utils:${{ steps.info.outputs.short_sha }}
            ghcr.io/fnndsc/utils:latest
          platforms: linux/amd64,linux/arm64
          push: true
